# Generated by Django 3.2.2 on 2021-05-17 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_author_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
